#ifndef COLORS_H
# define COLORS_H

# define COLOR_GREY_LIGHT 0x797979
# define COLOR_WHITE 0xFFFFFF
# define COLOR_BLACK 0x000000
# define COLOR_BLUE_INT 0x0000FF
# define COLOR_SKY_BLUE 0x15DAEA
# define COLOR_GREY 0xAAAAAA
# define COLOR_BROWN 0xBE8641

# define TEXT_FOREGROUND_COLOR 0
# define TEXT_BACKGROUND_COLOR 1

#endif
